In [ ]:
from google.colab import files
uploaded = files.upload()

Saving salary.csv to salary.csv
Saving canada_per_capita_income.csv to canada_per_capita_income.csv

In [ ]:
# Canada Income dataset

In [ ]:
import pandas as pd

df = pd.read_csv("canada_per_capita_income.csv")
df.head()

   year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [ ]:
# Using Library
# Expected Prediction: ≈ $41288


import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


df = pd.read_csv("canada_per_capita_income.csv")


X = df[['year']]
y = df['per capita income (US$)']


model = LinearRegression()
model.fit(X, y)


prediction_2020 = model.predict(pd.DataFrame([[2020]], columns=['year']))

print("Predicted per capita income in 2020:", prediction_2020[0])

Predicted per capita income in 2020: 41288.69409441762

In [ ]:
#Without using libraries

import numpy as np
import pandas as pd

df = pd.read_csv("canada_per_capita_income.csv")

X = df['year'].values
y = df['per capita income (US$)'].values


X_b = np.c_[np.ones(len(X)), X]


beta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

intercept = beta[0]
slope = beta[1]


prediction_2020 = intercept + slope * 2020

print("Intercept:", intercept)
print("Slope:", slope)
print("Predicted income in 2020:", prediction_2020)

Intercept: -1632210.7578560347
Slope: 828.4650752229782
Predicted income in 2020: 41288.694094381295

In [ ]:
# Salary dataset

In [ ]:
df2 = pd.read_csv("salary.csv")
df2.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [ ]:
# Using library
# Expected Prediction: ≈ $139000


import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv("salary.csv")

df = df.dropna()

X = df[['YearsExperience']]
y = df['Salary']

model = LinearRegression()
model.fit(X, y)

prediction = model.predict(pd.DataFrame([[12]], columns=['YearsExperience']))
print("Predicted salary for 12 years experience:", prediction[0])

Predicted salary for 12 years experience: 139049.6749539778

In [ ]:
# Without library

import numpy as np
import pandas as pd

df = pd.read_csv("salary.csv")
df = df.dropna()

X = df['YearsExperience'].values
y = df['Salary'].values


X_b = np.c_[np.ones(len(X)), X]


beta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

intercept = beta[0]
slope = beta[1]


prediction = intercept + slope * 12

print("Intercept:", intercept)
print("Slope:", slope)
print("Predicted Salary:", prediction)

Intercept: 26265.98773185526
Slope: 9398.640601843546
Predicted Salary: 139049.6749539778